// Generated by scripts/sync-page-seo.mjs from goalmatic.seo.json.
export const pageSeo = {
  "/": {
    "title": "Anthony Akpan | Software Engineer Portfolio",
    "description": "Software projects, apps, and writing by Anthony Akpan. Explore his work and download tools built for everyday use.",
    "image": "https://firebasestorage.googleapis.com/v0/b/goalmatics-prod.firebasestorage.app/o/sites%2F12ce3127-ff9d-45b4-967e-0acf4d68f71d%2Fseo-image-1773614599966?alt=media&token=b6ff75d7-de96-48d8-aaf1-29887b4351a6"
  },
  "/apps": {
    "title": "Apps by Anthony Akpan | macOS Utilities",
    "description": "Explore apps built by Anthony Akpan. Download WiFi Drop for local file transfers and Codex Account Switcher for managing accounts from the macOS menu bar.",
    "image": "https://kromate.dev/og/apps.png"
  },
  "/app/wifi-drop": {
    "title": "WiFi Drop | Local Wi-Fi File Transfer for Mac",
    "description": "Download WiFi Drop for Apple Silicon Macs. Transfer videos and files between your phone and laptop over the same Wi-Fi, with no cloud upload or phone app.",
    "image": "https://kromate.dev/og/wifi-drop.png"
  },
  "/app/codex-account-switcher": {
    "title": "Codex Account Switcher | macOS Menu Bar App",
    "description": "Download Codex Account Switcher for macOS 14 or later on Apple Silicon. Switch saved accounts from the menu bar and check remaining usage and reset times.",
    "image": "https://kromate.dev/og/codex-account-switcher.png"
  }
}
